INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric1}, ${tick11}, 10, 10, 10, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric1}, ${tick12}, 4, 4, 4, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric1}, ${tick13}, 3, 3, 3, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric1}, ${tick14}, 11, 11, 11, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric1}, ${tick15}, 6, 6, 6, 1);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric2}, ${tick11}, 2, 2, 2, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric2}, ${tick12}, 7, 7, 7, 1);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour1}, ${id_metric3}, ${tick11}, 10, 10, 10, 1);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'HOUR', ${hour2}, ${id_metric1}, ${tick21}, 12, 12, 12, 1);