INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick11}, 1, 10, 10, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick12}, 4, 7, 10, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick13}, 3, 4, 10, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick14}, 1, 11, 10, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick15}, 6, 6, 10, 1);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric2}, ${tick11}, 1, 10, 10, 1);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric2}, ${tick12}, 4, 7, 10, 1);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric3}, ${tick11}, 1, 10, 10, 1);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day2}, ${id_metric1}, ${tick21}, 1, 10, 10, 1);
