INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick11}, 1, 10, 19, 28);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick12}, 4, 7, 65, 56);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick13}, 3, 4, 22, 35);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick14}, 1, 11, 35, 19);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric1}, ${tick15}, 6, 6, 28, 87);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric2}, ${tick11}, 1, 10, 23, 46);
INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric2}, ${tick12}, 4, 7, 46, 31);


INSERT INTO centreon.rrd_aggregated(service, aggregation_unit, time_value, id_metric, previous_time_value, min, max, sum, count)
VALUES(${service}, 'DAY', ${day1}, ${id_metric3}, ${tick11}, 1, 10, 13, 47);

