INSERT INTO centreon.analytics_aggregated(id_metric,aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick11}, 1, 10, 10, 1);
INSERT INTO centreon.analytics_aggregated(id_metric,aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick12}, 4, 7, 10, 1);
INSERT INTO centreon.analytics_aggregated(id_metric,aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick13}, 3, 4, 10, 1);
INSERT INTO centreon.analytics_aggregated(id_metric,aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick14}, 1, 11, 10, 1);
INSERT INTO centreon.analytics_aggregated(id_metric,aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick15}, 6, 6, 10, 1);

