INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'HOUR', ${hour}, ${tick11}, 10, 10, 10, 1);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'HOUR', ${hour}, ${tick12}, 4, 4, 4, 1);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'HOUR', ${hour}, ${tick13}, 3, 3, 3, 1);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'HOUR', ${hour}, ${tick14}, 11, 11, 11, 1);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'HOUR', ${hour}, ${tick15}, 6, 6, 6, 1);
