INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick11}, 1, 10, 19, 28);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick12}, 4, 7, 65, 56);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick13}, 3, 4, 22, 35);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick14}, 1, 11, 35, 19);
INSERT INTO centreon.analytics_aggregated(id_metric, aggregation_unit, time_value, previous_time_value, min, max, sum, count)
VALUES(${id_metric}, 'DAY', ${day}, ${tick15}, 6, 6, 28, 87);


